### ISSUE TITLE
Observation sequencing

### ISSUE THREAD

**Issue by amullarney** [amullarney/TestFramework#9]
Each injected stimulus may be followed by a sequence of observations. As an observation completes, the next observation in sequence becomes current.  Having the completed observation do this 'promotion' rather than the stimulus avoids having a 'current' observation with status = complete while waiting for the 'promotion' to happen. That situation led to some convoluted logic when triggering an observation from a port activity: the target observation had not yet become eligible for invocation.

**Comment by johnrwolfe** [comment]
Merged #13, closing.
